DROP DATABASE IF EXISTS groupomania;
CREATE DATABASE groupomania;
USE groupomania;
CREATE TABLE users (id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, mail VARCHAR(255) NOT NULL UNIQUE, password VARCHAR(500) NOT NULL, prenom VARCHAR(100), nom VARCHAR(100), service VARCHAR(100));
CREATE TABLE posts (id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, text VARCHAR(3000), image VARCHAR(500), userId INTEGER NOT NULL, FOREIGN KEY(userId) REFERENCES users(id));
CREATE TABLE comments (id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, text VARCHAR(500), userId INTEGER NOT NULL, postId INTEGER NOT NULL, FOREIGN KEY(userId) REFERENCES users(id), FOREIGN KEY(postId) REFERENCES posts(id));
CREATE TABLE likesdislikes (id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, value BOOLEAN, userId INTEGER NOT NULL, postId INTEGER NOT NULL, FOREIGN KEY(userId) REFERENCES users(id), FOREIGN KEY(postId) REFERENCES posts(id));